name: InsightForge
run-name: ${{ github.actor }} is working on GitHub Actions ğŸš€
on: [push]
jobs:
  ChatGPT-Fine-Tuning:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ§ Install OpenAI tools for ${{ runner.os }}...
        run: pip install openai
      - name: ğŸ¼ Install Pandas for OpenAI...
        run: pip install openai[datalib]
      - name: ğŸ“ Clone the repo...
        uses: actions/checkout@v3
      - shell: bash
        name: ğŸ” Apply the API key to environment...
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo $OPENAI_API_KEY
          echo "boop"
      - name: ğŸ” Information gathering...
        run: |
          openai --help
          pwd
          ls
      - name: ğŸ–¥ï¸ Convert and validate jsonl...
        run: openai tools fine_tunes.prepare_data -f sample.jsonl -q
      - name: ğŸ¤– Integrate the content into AI
        run: openai api fine_tunes.create -t sample_prepared.jsonl -m davinci
      - name: ğŸ Deploy it I suppose
        run: echo "hi"
      - run: openai --help
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      - run: whoami