name: InsightForge
run-name: ${{ github.actor }} is working on GitHub Actions ğŸš€
on: [push]
jobs:
  ChatGPT-Fine-Tuning:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ§ Install OpenAI tools for ${{ runner.os }}...
        run: pip install openai
      - name: ğŸ“ Get the info to integrate to ChatGPT...
        run: cat ./sample.jsonl
      - name: ğŸ–¥ï¸ Convert and validate jsonl...
        run: |
          openai tools fine_tunes.prepare_data -f sample.jsonl
          openai api fine_tunes.create -t fine_tunes.prepare_data -m davinci
      - name: ğŸ Deploy it I suppose
        uses: actions/checkout@v3
      - run: openai --help
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      - run: whoami